// Category
export const ADD_NEW_CATEGORY_SUCCESS = 'ADD_NEW_CATEGORY_SUCCESS'
export const ADD_NEW_CATEGORY_FAIL = 'ADD_NEW_CATEGORY_FAIL'
export const SHOW_CATEGORY_LIST = 'SHOW_CATEGORY_LIST'
export const TURN_ON_CATEGORY_UPDATE_MODE = 'TURN_ON_CATEGORY_UPDATE_MODE'
export const TURN_OFF_CATEGORY_UPDATE_MODE = 'TURN_OFF_CATEGORY_UPDATE_MODE'

//Facet 
export const SHOW_FACET_LIST = 'SHOW_FACET_LIST'
export const TURN_ON_FACET_UPDATE_MODE = 'TURN_ON_FACET_UPDATE_MODE'

//Product
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS'
export const ADD_NEW_PRODUCT_FAIL = 'ADD_NEW_PRODUCT_FAIL'
export const SHOW_PRODUCT_LIST = 'SHOW_PRODUCT_LIST'
export const TURN_ON_PRODUCT_UPDATE_MODE = 'TURN_ON_PRODUCT_UPDATE_MODE'
export const TURN_OFF_PRODUCT_UPDATE_MODE = 'TURN_OFF_PRODUCT_UPDATE_MODE'

//Variant
export const SHOW_VARIANT_LIST_BY_PRODUCT = 'SHOW_VARIANT_LIST_BY_PRODUCT'
export const TURN_ON_VARIANT_UPDATE_MODE = 'TURN_ON_VARIANT_UPDATE_MODE'
export const TURN_OFF_VARIANT_UPDATE_MODE = 'TURN_OFF_VARIANT_UPDATE_MODE'
export const SHOW_VARIANT_LIST = 'SHOW_VARIANT_LIST'

//Facet Option
export const SHOW_FACET_OPTIONS_LIST = 'SHOW_FACET_OPTIONS_LIST'
export const SHOW_FACET_OPTIONS_BY_FACET_LIST = 'SHOW_FACET_OPTIONS_BY_FACET_LIST'
export const TURN_ON_FACET_OPTION_UPDATE_MODE = 'TURN_ON_FACET_OPTION_UPDATE_MODE'

//Popup
export const SHOW_POPUP = 'SHOW_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

//Customer
export const GET_CUSTOMER_INFO = 'GET_CUSTOMER_INFO'
export const SHOW_CUSTOMER_LIST = 'SHOW_CUSTOMER_LIST'
export const SHOW_CUSTOMER_ORDERS = 'SHOW_CUSTOMER_ORDERS'
export const SHOW_CUSTOMER_PROFIT = 'SHOW_CUSTOMER_PROFIT'

//Import 
export const PICK_CUSTOMER = 'PICK_CUSTOMER'
export const PICK_VARIANT = 'PICK_VARIANT'
export const UPDATE_VARIANT_UNIT = 'UPDATE_VARIANT_UNIT'
export const UPDATE_VARIANT_PRICE = 'UPDATE_VARIANT_PRICE'
export const REMOVE_VARIANT_UNIT = 'REMOVE_VARIANT_UNIT'

//Stock
export const SHOW_STOCK_LIST = 'SHOW_STOCK_LIST'
